default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_520_ci
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: valetbike_development
  username: root
  password: Deda3435

test:
  <<: *default
  database: valetbike_test
  username: root
  password: Deda3435

production:
  <<: *default
  database: valetbike_production
  username: root
  password: Deda3435a]
